formats: ["oas2"]
extends:
  - 'spectral:oas'
functions: [equals]

rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight

  consumed-as-produced:
    description: Mediatype mismatch between consumes and produces parameters.
    message: Mediatype mismatch between consumes and produces parameters.
    given: $.paths.[*].post
    recommended: true
    type: style
    severity: warn
    then:
      function: equals
      functionOptions:
        left: consumes
        right: produces
  
  response-code-detection:
    description: Detects missing response codes as required by the styleguide.
    message: This operation is missing response codes.
    given: $.paths.[*].[*].responses
    recommended: true
    type: style
    severity: info
    then:
      function: pattern
      functionOptions:
        match:
          - 200
          - 400